# Configurações do Banco de Dados H2 (Em memória)
spring.datasource.url=jdbc:h2:mem:luffy_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Ativa o console web do H2 para você ver as tabelas (http://localhost:8080/h2-console)
spring.h2.console.enabled=true

# Atualiza a estrutura das tabelas automaticamente com base no arquivo Score.java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true